// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Button button19;
    
    private HollyLibrary.HDateEdit hdateedit1;
    
    private HollyLibrary.HFontPicker hfontpicker1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private HollyLibrary.HSimpleList hsimplelist1;
    
    private Gtk.Button button1;
    
    private Gtk.Button button2;
    
    private Gtk.Button button3;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button19 = new Gtk.Button();
        this.button19.CanFocus = true;
        this.button19.Name = "button19";
        this.button19.UseUnderline = true;
        this.button19.Label = Mono.Unix.Catalog.GetString("button19");
        this.hbox2.Add(this.button19);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.button19]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.hdateedit1 = new HollyLibrary.HDateEdit();
        this.hdateedit1.Events = ((Gdk.EventMask)(256));
        this.hdateedit1.Name = "hdateedit1";
        this.hdateedit1.CurrentDate = new System.DateTime(0);
        this.hbox2.Add(this.hdateedit1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.hdateedit1]));
        w2.Position = 1;
        this.vbox2.Add(this.hbox2);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hfontpicker1 = new HollyLibrary.HFontPicker();
        this.hfontpicker1.Events = ((Gdk.EventMask)(256));
        this.hfontpicker1.Name = "hfontpicker1";
        this.vbox2.Add(this.hfontpicker1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hfontpicker1]));
        w4.Position = 1;
        w4.Expand = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.hsimplelist1 = new HollyLibrary.HSimpleList();
        this.hsimplelist1.CanFocus = true;
        this.hsimplelist1.Name = "hsimplelist1";
        this.hsimplelist1.HeadersClickable = true;
        this.hsimplelist1.ItemHeight = 20;
        this.hsimplelist1.SelectedIndex = 0;
        this.hsimplelist1.OwnerDraw = true;
        this.GtkScrolledWindow.Add(this.hsimplelist1);
        this.vbox2.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
        w6.Position = 2;
        // Container child vbox2.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("button1");
        this.vbox2.Add(this.button1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.button1]));
        w7.Position = 3;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("sort");
        this.vbox2.Add(this.button2);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.button2]));
        w8.Position = 4;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("multiple selection test");
        this.vbox2.Add(this.button3);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.button3]));
        w9.Position = 5;
        w9.Expand = false;
        w9.Fill = false;
        this.Add(this.vbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 546;
        this.DefaultHeight = 309;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.hdateedit1.Changed += new System.EventHandler(this.OnHdateedit1Changed);
        this.hfontpicker1.FontChange += new HollyLibrary.FontEventHandler(this.OnHfontpicker1FontChange);
        this.hsimplelist1.OnSelectedIndexChanged += new System.EventHandler(this.OnHsimplelist1OnSelectedIndexChanged);
        this.hsimplelist1.OnDrawItem += new HollyLibrary.DrawItemEventHandler(this.OnHsimplelist1OnDrawItem);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
    }
}
