// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.Button button1;
    
    private HollyLibrary.GtkControl gtkcontrol1;
    
    private Gtk.Button button2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = "MainWindow";
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = "button1";
        this.vbox1.Add(this.button1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.button1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.gtkcontrol1 = new HollyLibrary.GtkControl();
        this.gtkcontrol1.Name = "gtkcontrol1";
        this.vbox1.Add(this.gtkcontrol1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.gtkcontrol1]));
        w2.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = "button2";
        this.vbox1.Add(this.button2);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.button2]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 577;
        this.DefaultHeight = 400;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.gtkcontrol1.KeyUp += new HollyLibrary.GcKeyUp(this.OnGtkcontrol1KeyUp);
        this.gtkcontrol1.KeyDown += new HollyLibrary.GcKeyDown(this.OnGtkcontrol1KeyDown);
        this.gtkcontrol1.KeyPressed += new HollyLibrary.GcKeyPressed(this.OnGtkcontrol1KeyPressed);
        this.gtkcontrol1.MouseMove += new HollyLibrary.GcMouseMove(this.OnGtkcontrol1MouseMove);
        this.gtkcontrol1.MouseUp += new HollyLibrary.GcMouseUp(this.OnGtkcontrol1MouseUp);
        this.gtkcontrol1.MouseDown += new HollyLibrary.GcMouseDown(this.OnGtkcontrol1MouseDown);
        this.gtkcontrol1.MouseClick += new HollyLibrary.GcMouseClick(this.OnGtkcontrol1MouseClick);
        this.gtkcontrol1.MouseDoubleClick += new HollyLibrary.GcMouseDoubleClick(this.OnGtkcontrol1MouseDoubleClick);
        this.gtkcontrol1.MouseWheel += new HollyLibrary.GcMouseWheel(this.OnGtkcontrol1MouseWheel);
    }
}
