// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HollyLibrary {
    
    
    public partial class FolderChooserDialog {
        
        private Gtk.VBox vbox1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private HollyLibrary.HTreeView FolderTree;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Button BtnNewFolder;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget HollyLibrary.FolderChooserDialog
            this.Name = "HollyLibrary.FolderChooserDialog";
            this.Title = Mono.Unix.Catalog.GetString("FolderChooserDialog");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.BorderWidth = ((uint)(2));
            this.Decorated = false;
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            this.FocusOnMap = false;
            // Container child HollyLibrary.FolderChooserDialog.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(4));
            // Container child vbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.GtkScrolledWindow.BorderWidth = ((uint)(2));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.FolderTree = new HollyLibrary.HTreeView();
            this.FolderTree.CanFocus = true;
            this.FolderTree.Name = "FolderTree";
            this.FolderTree.HeadersClickable = true;
            this.FolderTree.NodeIconVisible = false;
            this.FolderTree.IsCheckBoxTree = false;
            this.FolderTree.Editable = false;
            this.GtkScrolledWindow.Add(this.FolderTree);
            this.vbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
            w2.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox1.Add(this.hseparator1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.BtnNewFolder = new Gtk.Button();
            this.BtnNewFolder.CanFocus = true;
            this.BtnNewFolder.Name = "BtnNewFolder";
            this.BtnNewFolder.UseStock = true;
            this.BtnNewFolder.UseUnderline = true;
            this.BtnNewFolder.Label = "gtk-new";
            this.vbox1.Add(this.BtnNewFolder);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.BtnNewFolder]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 318;
            this.DefaultHeight = 271;
            this.Hide();
            this.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnButtonPressEvent);
            this.FolderTree.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnFolderTreeButtonPressEvent);
            this.FolderTree.BeforeNodeExpand += new HollyLibrary.NodeBeforeExpandHandler(this.OnFolderTreeBeforeNodeExpand);
            this.FolderTree.CursorChanged += new System.EventHandler(this.OnFolderTreeCursorChanged);
            this.FolderTree.RowActivated += new Gtk.RowActivatedHandler(this.OnFolderTreeRowActivated);
            this.BtnNewFolder.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnBtnNewFolderButtonPressEvent);
        }
    }
}
