// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HollyLibrary {
    
    
    public partial class HDateEdit {
        
        private HollyLibrary.HBaseComboBox comboBox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget HollyLibrary.HDateEdit
            Stetic.BinContainer.Attach(this);
            this.Name = "HollyLibrary.HDateEdit";
            // Container child HollyLibrary.HDateEdit.Gtk.Container+ContainerChild
            this.comboBox = new HollyLibrary.HBaseComboBox();
            this.comboBox.Events = ((Gdk.EventMask)(256));
            this.comboBox.Name = "comboBox";
            this.Add(this.comboBox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
