// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    
    
    public partial class MainWindow2 {
        
        private HollyLibrary.HLabel hlabel1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget test.MainWindow2
            this.Name = "test.MainWindow2";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow2");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child test.MainWindow2.Gtk.Container+ContainerChild
            this.hlabel1 = new HollyLibrary.HLabel();
            this.hlabel1.Name = "hlabel1";
            this.hlabel1.LabelProp = Mono.Unix.Catalog.GetString("hlabel1");
            this.hlabel1.TextOweritesIcon = false;
            this.hlabel1.HorizontalLine = false;
            this.Add(this.hlabel1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
